# Generated by Django 5.2.7 on 2026-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('formatted_content', models.TextField()),
                ('transcribe_type', models.CharField(choices=[('verbatim', 'Verbatim'), ('english', 'English Translation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('upload_duration', models.FloatField(default=0)),
                ('transcription_duration', models.FloatField(default=0)),
                ('total_duration', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
